### ISSUE TITLE
Data cells in leaderboard should be grayed out if the star has not been completed

### ISSUE THREAD

**Issue by jonashogstrom** [jhogstrom/aoc-highscores2#64]
Players that have not completed a star does not have the final score for that cell, so the cell should be grayed out in tables like leaderboard, tobiiscore, positionforstar.

here is a sample of what it looked like in the original implementation
![image](https://user-images.githubusercontent.com/1035652/144377460-46056262-8a3b-4934-9ab9-2e224c3f076c.png)

**Comment by jonashogstrom** [comment]
When stars are not completed in chronological order, there will be interesting gaps in the series, and values will be non-final even if they are not grayed out. This is OK.
![image](https://user-images.githubusercontent.com/1035652/144377711-90d0b077-58e5-4828-a882-7ffdf4583959.png)

**Comment by jhogstrom** [comment]
I have a fix for this, but since you changed from score to pos in LeaderBoard I am not sure we'll get exactly what you wanted :)
